.gitignore
go.mod
go.sum
main.go

This PR implements a filter by with glob support, so we can use to filter for a specific env name or for one with a prefix.
I also used the opportunity to implement a better cli, with support for required flags.

Implement name with glob support and force

---

.codefresh/auto-prune/pipeline.yml
.codefresh/auto-prune/spec.yml
.codefresh/build/pipeline.yml
.codefresh/build/spec.yml
Makefile
README.md
prune/main.go

This allow us to have multiple environments so we can test things.

Make it possible to use multiple environments

---

.codefresh/build/pipeline.yml
Dockerfile
deploy/deploy

Allow passing the char repo to docker as an argument and pin the chart version.

Build image with chart repo url and fixed version

---

Dockerfile
deploy/deploy

[ch20192](https://app.clubhouse.io/findhotel/story/20192/codefresh-fix-the-problem-with-the-name-of-namespace-must-be-no-more-than-63-characters)
- New packages added to install on `Dockerfile`
- New commands added on `deploy` file to fix the problem with the namespace name
Build: https://g.codefresh.io/build/5f2269f68a6b246b66f3f1a1

[ch20192] - fix the problem with the namespace name

---

.codefresh/auto-prune/pipeline.yml
.codefresh/auto-prune/spec.yml
.codefresh/cd/spec.yml
.codefresh/ci/spec.yml
prune/main.go

Implement checking if the pr connect to the environment has already been merged, so we delete the environment.

[ch20440] Implement auto prune using github integration

---

deploy/deploy

[ch21310](https://app.clubhouse.io/findhotel/story/21310/codefresh-check-the-deployment-review-step-on-ci-pipeline)
Added the export of the result from the helm test to use it on CI pipeline.
Pipeline:
https://g.codefresh.io/build/5f450c76f32d43401819a9ee?step=deploy&tab=output&logs=terminal

[ch21310] - added the export of the result from the helm test

---

Dockerfile

https://app.clubhouse.io/findhotel/story/21562/k8s-change-the-default-ssl-cert-on-nginx-ingress-for-all-services
- certbot and aws-cli packages added

[ch21562] - certbot and aws-cli packages added

---

Dockerfile

https://app.clubhouse.io/findhotel/story/21384/remove-verbose-and-unnecessary-variables-from-cf-review-env
CD - https://g.codefresh.io/build/5f5f3a7ca357178e678040e4
CI - https://g.codefresh.io/build/5f5f398429b4b83396c6ff6e

[ch21384] - docker file updated

---

deploy/deploy

https://app.clubhouse.io/findhotel/story/21384/remove-verbose-and-unnecessary-variables-from-cf-review-env

[ch21384] - fix the deploy script

---

deploy/deploy

https://app.clubhouse.io/findhotel/story/21382/remove-need-for-secrets-file-from-cf-review-env-app

[ch21382] - secret env file tratament added

---

charts/cf-review-env/Chart.yaml
charts/cf-review-env/values.yaml
deploy/deploy

https://app.clubhouse.io/findhotel/story/21563/remove-need-to-specific-values-file-on-cf-review-env

[ch21563]Added values.yaml file

---

charts/README.md
charts/cf-review-env/Chart.yaml
charts/cf-review-env/templates/deployment.yaml
charts/cf-review-env/templates/hpa.yaml
charts/cf-review-env/templates/service.yaml
charts/cf-review-env/templates/tests/test-connection.yaml
charts/cf-review-env/values.yaml
deploy/deploy

https://app.clubhouse.io/findhotel/story/22633/create-the-development-pipeline-to-the-labrador-repository-on-the-codefresh-service
- Readme file updated
- Chart version updated
- Added default values for the parameters on the Deployment file and removed on the values file
- Added treatment for the docker dind on the Deployment file
- Added default values for the parameters on the HPA file and removed on the values file
- Added default values for the parameters on the Service file and removed on the values file
- Added treatment for Helm Test on the tests folder
- Removed unnecessary values on the `Values.yaml` file
- Deploy file updated with new chart version

[ch22633] - Helm Chart Updated with new settings and version

---

charts/cf-review-env/Chart.yaml
charts/cf-review-env/templates/deployment.yaml
deploy/deploy

- Deploy script updated with the new bump version
- Deployment file updated
- Chart file updated with the new bum version
NOTE: Now in the EKS production environment we have the `startupProbe` enabled.

chart bump version 027

---

deploy/deploy
prune/main.go

Check if a env is alive using pr number and branch name, therefore if pr number is nor present we can still deleted the env.

Add branch name as annotation and use it to prune

---

charts/cf-review-env/Chart.yaml
charts/cf-review-env/templates/deployment.yaml
deploy/deploy

This will improve performance and mitigate the possibility that we fall into the ecr expired token problem.

[ch25106] Change default images pull policy to IfNotPresent

---

charts/cf-review-env/Chart.yaml
charts/cf-review-env/templates/deployment.yaml
charts/cf-review-env/values.yaml
charts/docs/helm-template.md

Expose the KR_HOST variable with the host name of the app being deployed.

[ch27871] Expose KR_HOST variable to container

---

charts/cf-review-env/templates/deployment.yaml
deploy/deploy

Bump the version on the deploy script and fix an issue with dind. When dind enable the env was not getting injected.

Make KR_HOST be inject also when using dind

---

deploy/deploy

https://app.clubhouse.io/findhotel/story/29148/improve-deploy-script-of-review-env-to-remove-the-helm-chart-and-reinstall-it-automatically
First installation:
Second installation and so on:

[ch29148] - helm uninstall command added

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml

Start publishing the kube-review-prune chart.

[ch22704] Change github actions to publish kube review prune chart

---

deploy/deploy

This adds some log messages showing what is getting load and also removes a piece of logic that is not needed anymore.

Make loading secrets more clear and with log messages

---

scripts/README.md
scripts/helm-chart-purge.sh

https://app.clubhouse.io/findhotel/story/29913/remove-old-charts-from-our-public-helm-repos

[ch29913] - helm chart purge script created

---

deploy/deploy

https://app.clubhouse.io/findhotel/story/27851/create-a-dd-index-to-make-easier-to-find-review-env-logs
It was tested in this job:
https://g.codefresh.io/build/6050d963fab83a84aef5abf3

[ch27851] - expose the URL of the logs in the Datadog

---

LICENSE
README.md

As part of the process of revamping the docs, this is the first task of a better readme and a license file.

Add revamped README and LICENSE

---

README.md
docs/introduction.md

Just add introduction docs page to the docs. This is a first version. We can improve this later with images and links to necessary resources.

[ch31801] Add the introduction docs page

---

Dockerfile
deploy/deploy

To make easier to test and better tutorials we are making possible to run the deploy command locally. Also, this is getting rid of the cf-step-helm dependency. I also took the time to make some more parameters non requirement.

Allow execution of deploy command without docker

---

README.md
docs/files/aws_route53-dns_change.json
docs/files/cert-manager-certificate.yaml
docs/files/cert-manager-letsencrypt-aws-route53-clusterissuer.yaml
docs/files/route_53_change_policy.json
docs/files/values.yaml
docs/tutorial.md

The idea on this doc is to allow anyone to follow a simple doc to setup the basic infra and then be able to deploy a simple review env.

Introduces the new docs session called tutorial 

---

src/deploy/deploy

Adding more debug info, like showing the url being tested as well as the output if the test fails. Also, I added a retry to minimize the chances of failures due to simple transient errors.

Add more info to test connection execution to aid debugging

---

docs/introduction.md
docs/tutorial.md
src/deploy/deploy

- Cosmetics applied to documentation format standard.
- Post-Install function moved to Pre-Install to assure run whenever deploy is run

refactor: URL print from postinstall to preinstall function

---

src/prune/charts/kube-review-prune/Chart.yaml

App version has to be updated after merging [this](https://github.com/FindHotel/kube-review/pull/109) PR

update app version

---

src/deploy/deploy

Adding `JOB_URL` as annotation during deployments to make it easier to know which job built the review environment.

Adding the JOB_URL variable as annotation during deployments

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml
src/prune/main.go

https://app.shortcut.com/findhotel/story/49171/check-codefresh-dependencies-on-kube-review-and-kube-review-prune-project
- CI workflow updated by adding a new Helm repository, plugin and credentials
- CD workflow updated by adding a new Helm repository, plugin and credentials
- Removed the `cf-review-env` label
It has been tested here:
https://github.com/FindHotel/kube-review/actions/runs/2782942996

[sc-49171] - Removing Codefresh dependencies

---

CODE_OF_CONDUCT.md
README.md
docs/customization.md
docs/introduction.md
docs/reference.md
docs/tutorial.md
src/deploy/resources/base/vpa.yml

- Docs updated adding the VPA service

Docs updated adding the VPA service

---

src/deploy/resources/base/deployment.yml

Add a default node selector

---

.github/workflows/ci.yaml
Dockerfile
src/deploy/resources/base/httpscaledobject.yml
src/deploy/resources/base/patches/httpscaledobject.patch.json

Due to the update of the version of the httpscaledobject to v0.8.0, the yaml file has to be edited

fix: httpscaledobject yaml
