viodotcom/kube-review

- .codefresh/build/pipeline.yml
- Dockerfile
- charts/README.md
- charts/cf-review-env/.helmignore
- charts/cf-review-env/Chart.yaml
- charts/cf-review-env/templates/NOTES.txt
- charts/cf-review-env/templates/_helpers.tpl
- charts/cf-review-env/templates/deployment.yaml
- charts/cf-review-env/templates/hpa.yaml
- charts/cf-review-env/templates/ingress.yaml
- charts/cf-review-env/templates/service.yaml
- charts/cf-review-env/templates/serviceaccount.yaml
- charts/cf-review-env/templates/tests/test-connection.yaml
- deploy/deploy
Add a deploy command that can be used to install the review env chart. 
The helm chart was originally developed internally. In this PR I'm mostly copying and changing the name.
> [ch19928] Implement deploy command with a review env chart

- deploy/deploy
[ch20623](https://app.clubhouse.io/findhotel/story/20623/check-validation-time-of-ssl-certificate-cert-manager-service)
It is necessary to change the number of characters of the `namespace` name because today we are using the variable `$NAMESPACE` to create the URL (ingress host) for the review environment and the number of characters is too long for the `letsencrypt` service validate the SSL certificate.
Ref.:
- https://community.letsencrypt.org/t/ssl-for-a-63-character-max-number-of-characters-domain-name-s/36387
- https://github.com/certbot/certbot/issues/1915
> [ch20623] - change the size of the namespace name

- .codefresh/auto-prune/pipeline.yml
- .codefresh/auto-prune/spec.yml
- Dockerfile
- deploy/deploy
- prune/main.go
Add labels to the k8s namespace that we create for each deployment. The labels will then be used when search for all cf-review-envs in the cluster, but also to get the update at time and later on the pr number.
> [ch20441] Use labels to identify cf-review deployments to be pruned

- Dockerfile
- deploy/deploy
[ch21204](https://app.clubhouse.io/findhotel/story/21204/check-the-memory-metrics-on-the-hpa-file-in-the-helm-chart)
- The `kubectl` command needs to update because in our `helm templates` we are checking the version from the command to use the current `apiVersion`.
- `--dry-run` is deprecated and can be replaced with `--dry-run=client`
For example: 
`{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}`
Note: I trying to update it with the intent to fix the problem with HPA metrics from the pods.
> [ch21204] - Added new version of the kubectl command line

- charts/cf-review-env/Chart.yaml
- charts/cf-review-env/templates/tests/test-connection.yaml
- deploy/deploy
During implementation of the website-proxy project I had problems with the connection test. Nginx only responds to requests of specific addresses, therefore the connection test was failing as it uses the local ip. On this PR I'm changing the connection test to use the ingress address, which is much better test to perform, as it will test the app end to end, and also make deployments like nginx work. I'm also introducing a parameter to disable the connection test if needed, and I'm making possible to specify the chart version, so we can test things easily.
> Improvement to connection test

- deploy/deploy
To allow multiple concurrent deployments of a review env we need to copy the kuke config folder for each execution. This is necessary because kubectl locks the config for each execution. This is needed in pipelines deploy multiple review envs concurrently, like the website one.
> [ch23168] Allow multiple concurrent deployments in the same kubectl

- TODO.md
- charts/cf-review-env/Chart.yaml
- charts/cf-review-env/templates/deployment.yaml
- charts/cf-review-env/values.yaml
- deploy/deploy
- Added new bump version
- Added default value for the startupProbe and livenessProbe
- Changed the time of failureThreshold from 100 to 60
- Deploy script updated with new bump version
> Chart bump version 025

- charts/cf-review-env/Chart.yaml
- charts/cf-review-env/templates/deployment.yaml
- deploy/deploy
Ref.: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
- Chart bump version 0.2.8
- Added treatment to fix the problem on the secrets when they are updated and the pods don't.
> [ch24233] - chart bump version 028

- .gitignore
- Makefile
- deploy/deploy
- prune/main.go
https://app.clubhouse.io/findhotel/story/24359/remove-limit-of-63-characters-for-branch-name
Start using annotation instead of labels for data about the review env. This fix the problem with branches with long names.
> [ch23748] Use annotation to store env data, fix for long branch names

- deploy/deploy
- prune/main.go
Implements support for non ephemeral envs (fixed). This is useful for teams that need to keep some envs. Non ephemeral envs won't be deleted. But also, we can now specify their names.
> [ch24709] Implement support for non ephemeral environments

- deploy/deploy
Adds support for pre/post hook into the deploy script. This will be used by the github update script. This is useful because we can easily access the env vars of the environment.
My first attempt was to use codefresh hooks, but I could not find a way to tell the hooks which env was bein deployed.
> [ch24337] Add support for calling pre/post hooks

- README.md
- TODO.md
- charts/cf-review-env/Chart.yaml
- charts/cf-review-env/templates/deployment.yaml
- deploy/deploy
https://app.clubhouse.io/findhotel/story/27047/remove-the-step-to-create-the-secrets-in-eks-for-all-deployments
- removed the secrets of the ECR repositories
- new bump version 0.2.12
- updated readme file
- removed TODO file, it's no longer necessary
Job: https://g.codefresh.io/build/5fdc88f22b1c4c892ea70de0
Note: It was deployed in the staging environment
> [ch27047] - removed the secrets of the ECR repositories

- deploy/deploy
This is a requirement that came up with the work that @gabrielmanara is doing to add end to end tests to the website. In such situation we need to know the url of each env deployed. Because they might override one another we need this prefix.
> Prefix url variable with the app prefix

- deploy/deploy
In cases where the app prefix has a dash (-) we need to replace by underscore (_) as dash is not a valid var name.
> Replace dash by underscore when using app prefix to create url var

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
In order to move forward with our plan to make kube-review a true open source project, we need to have the ci/cd pipelines into a public place. Therefore we migrate from CF to github actions.
> [ch27570] Move ci/cd pipelines to github actions

- charts/docs/helm-chart.md
- charts/docs/helm-template.md
- charts/kube-review-prune/.helmignore
- charts/kube-review-prune/Chart.yaml
- charts/kube-review-prune/templates/_helpers.tpl
- charts/kube-review-prune/templates/clusterole.yaml
- charts/kube-review-prune/templates/clusterolebinding.yaml
- charts/kube-review-prune/templates/cronjob.yaml
- charts/kube-review-prune/templates/serviceaccount.yaml
- charts/kube-review-prune/values.yaml
- prune/main.go
Instead of using CF cron build, this will implement the kube-review-prune process a k8s cron job. This will make easier for people to install both prune and app as helm charts. One more step towards a real open source project that can be used outside FH.
> [ch22704] Implement kube review prune job as a k8s cronjob

- charts/docs/helm-chart.md
- charts/docs/helm-template.md
- charts/kube-review-prune/.helmignore
- charts/kube-review-prune/Chart.yaml
- charts/kube-review-prune/templates/_helpers.tpl
- charts/kube-review-prune/templates/clusterole.yaml
- charts/kube-review-prune/templates/clusterolebinding.yaml
- charts/kube-review-prune/templates/cronjob.yaml
- charts/kube-review-prune/templates/serviceaccount.yaml
- charts/kube-review-prune/values.yaml
- prune/main.go
We never really used the CF environments feature. So, we better remove this dead code as it will also make easier to migrate the prune job to a k8s cron job, less dependencies.
> Remove removeal of cf environment as we don't use it anymore

- charts/kube-review-prune/templates/clusterole.yaml
- charts/kube-review-prune/templates/clusterolebinding.yaml
Add required labels by helm and use a proper name.
> Add missing labels and proper resource name to kube-review-prune chart

- prune/main.go
The logic was inverted, so sometimes live prs were deleted and dead prs were not :(
> Fix prune job to properly remove merged PRs

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
Start using the public image from docker hub registry.
> [ch27571] Start using dockerhub instead of ecr

- charts/kube-review/Chart.yaml
- charts/kube-review/templates/ingress.yaml
- deploy/deploy
https://app.clubhouse.io/findhotel/story/31379/fix-warnings-on-kubernetes-1-19
This warning is about the Ingress extensions:
`extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
New syntax for ingress template:
https://kubernetes.io/docs/concepts/services-networking/ingress/
It was tested here:
https://g.codefresh.io/build/6065cd5f697c2246551478cc
> [ch31379] - fixing warnings for the ingress extensions

- charts/kube-review-prune/values.yaml
The installation of the kube-review-prune chart should use the docker hub image. So, this changes the default values file to point to the correct docker registry.
> Change prune chart default values file to use docker hub image

- .github/workflows/ci.yaml
- charts/kube-review-prune/Chart.yaml
Currently, for devel helm charts we are creating them with this standard
`0.0.1+${{ github.sha }} = 0.0.1+36388f21f99c05de85406c367ab4915a740fad4b`
And it is making hard to identify what is the latest version of the chart when we need to run `helm install` command, for example, for the `kube-review-prune` the latest version is `0.0.1+e7a5a7f847bef724c9d35b11e29eb154c14413c2` and when we try to install it we are getting the version `0.0.1+c10329c62c028dcf8832d60bdd733c939a759f78`.
Trying to fix it, I'd like to purpose a new standard following [terraform documents](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#devel) and using `current time`, like this:
`0.0.1-${{steps.date.outputs.date}} = 0.0.1-2021-05-27-10-00-33`
> ci flow changed to use current time

- charts/kube-review/Chart.yaml
- deploy/deploy
https://app.clubhouse.io/findhotel/story/31792/improve-version-installing-of-kube-review
It was tested here:
Kube Review current version (APP version 0.5): https://g.codefresh.io/build/60c86afcdc923c3b4009ac4d
Kube Review a new bump version (APP version 0.6): https://g.codefresh.io/build/60c86c99850bdb6aec2222c7
Note: I did these tests just to confirm if we really will get the latest version every time.
> [ch31792] - pin version of kube review chart version removed

- README.md
- docs/introduction.md
- docs/reference.md
Adds a new docs section called reference, with all options for both deploy and prune components. Also, I'm fixing some name mistakes in other docs.
> [ch31803] Add reference docs section

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
Start triggering the cd pipeline on releases. This will allow us to have versioned releases instead of the current latest/master schema. This will allow us to pin the version of kube-review used in the pipelines. Which makes easy to select which release one wants to use. Besides, this is a much better practice.
After this PR is merged I will update all pipelines to point to the 0.5 release, the current one.
> Trigger actions cd pipeline only when a release is published

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
Quick fix to make CI ignore tag builds and to only have one build when a tag is published.
> Ignore tags on ci flow and avoid dupe build on cd

- src/deploy/deploy
- src/deploy/resources/base/kustomization.yaml
Remove version from resource files to make release easier. Also, move instance value to annotation instead of labels as the prune job expects it to be there.
> Remove version from resource files and move instance value to annotations

- src/deploy/deploy
Forcing use of head can break some projects that do not allow head as http method.
Describing the deployment after rollout makes easier to debug issues.
> Do not force head on connection test and describe deployment after rollout

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- docs/customization.md
- docs/reference.md
- docs/tutorial.md
- src/deploy/resources/base/deployment.yml
- src/deploy/resources/base/patches/deployment.patch.json
- Changing `Kube-Review` deployment file to use only one argument in `Container Image`, making it possible to use a full URL of the Image URL repository plus tag.
- Changing parameter `KR_IMAGE_URL` to `KR_IMAGE`
- Github Workflow updated fixing an error related to helm `v3.7.0`.
Since `Helm version v3.7.0` there is a bug related to [helm push - issue](https://github.com/chartmuseum/helm-push/issues/109). As an alternative, there is this [pull request](https://github.com/chartmuseum/helm-push/pull/110)
With these changes will be possible to use only one parameter to specify the `Docker Image` on deployments in `Kube-Review`, like this: `KR_IMAGE=nginx:stable`
> Changing Container Image field to use only one argument as a value

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
`Helm Push Plugin` has a new [version v0.10.0](https://github.com/chartmuseum/helm-push/releases/tag/v0.10.0) released to fix the error related to `oci://` protocol.
Ref.: https://github.com/chartmuseum/helm-push/issues/109 and https://github.com/chartmuseum/helm-push/pull/110
> re-using helm-push plugin again in GH workflow

- src/deploy/deploy
https://app.shortcut.com/findhotel/story/39737/show-pods-logs-in-kube-review-when-used-the-kr-verbose-parameter
- Adding `kubectl logs` command to expose POD logs from deployments
It has been tested:
https://g.codefresh.io/build/6203db9cc7bfd729393d3d16
> [ch39737] - adding kubectl log command for verbose mode

- src/deploy/resources/base/service.yml
Trying to fix the errors below in `ingress-nginx service`, I have added a selector in service.yaml file:
```
selector:
app.kubernetes.io/name: kube-review
```
> [ingress-nginx] - adding selector in service.yaml file

- src/deploy/deploy
- Describe deployed pods no longer depends on verbose = true.
- Logs are collected from Deployed pods and printed to the output console.
> feat: logs & describe from deployed Pods

- src/prune/charts/kube-review-prune/templates/cronjob.yaml
Changing the cronjob API version from `batch/v1beta1` to `batch/v1`.
`2022-05-25 12:40:28 UTC | CLUSTER | WARN | (klog@v1.0.1-0.20200310124935-4ad0115ba9e4/klog.go:1207 in Warning) | batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob`
> changing the cronjob API version to batch/v1

- Dockerfile
- docs/reference.md
- src/restart/restart
Implement a restart command, so that we can just restart review envs without re-deploy. This makes it possible to restart a review env outside of the repo that contains the overlay files.
Used here https://github.com/FindHotel/github-actions/pull/13/files#diff-abeec520ad6e301dd9d714135a1c647c0cd073c46ded4817eddcf1b20fac57dcR34 and here https://github.com/FindHotel/raa-profiles/pull/1676/files#diff-5e0e118103b95ac1f259bb84f2c73c382a5f7cdfc0fe816f2c867765a5016f0aR110
> [ch52127] Add a restart command

- src/prune/main.go
Currently non-ephemeral envs are never pruned. Sometimes there are non-ephemeral envs that arent being used. 
Added an expiration for non-ephemeral environments. The new default expiration for ephemeral envs is 30 days
> Improve the Kube Review Prune project to check the review envs non-ephemerals

- .github/workflows/cd.yaml
With this method images will be added with a major release tag. This tag can be referenced from other pipelines as latest stable from a determined major version removing the demand of bumping specific version to use the latest stable version within a major release.
Reference - Stable Tags:
https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/
> feat: get major version and set as image tag

- src/prune/main.go
Currently when a PR is merged regardless of wheather the env is ephemeral or not, the env will be deleted. In this PR, I added a condition that will stop the deletion of the env if the PR is merged and the env is non-ephemeral
> Stop deletion of non-ephemeral envs when PR is merged

- src/deploy/deploy
I've resisted this change in the past, but I think it's necessary. Instances take a long time to get ready, sometimes more than 5 minutes. So, if we try to deploy and there is no room in the cluster, it will take a while for a new instance to get ready. This is especially true with the labrador project, which uses big instances.
> Increate deploy timeout to 10m

- docs/reference.md
- src/deploy/deploy
Add support for shared path, a path that when provided by the user will be copied to the root of overlay, from which the kustomize will execute. This path will then be available as a special folder named `__shared_path`, which can be referenced in the kustomize:
```
configMapGenerator:
- name: shared-path
files:
- __shared_path/bar.sh
- __shared_path/foo.sh
```
With this, one can use Kustomize configMapGenerator, to load files from the host into Kubernetes, that later can be mounted as a volume. Useful when one has a script that needs to be executed by a resource in Kubernetes but the resource is not available in an image.
> Add support for shared path

- .github/workflows/ci.yaml
Setting the correct branch name value in the CI workflow
It has been tested here:
https://github.com/FindHotel/kube-review/actions/runs/4385959934/jobs/7679362832
> fixing CI workflow

- src/deploy/resources/base/httpscaledobject.yml
In some occasions, integrated tests may mistakenly fail due to a scale down after initial deploy. 
This change will increase Keda `cooldownperiod` from default 300s to 900s.
https://keda.sh/docs/2.11/concepts/scaling-deployments/#cooldownperiod
> chore: change keda cooldown period from default 300s to 900s

- src/deploy/deploy
Intermittently, integrated tests within the workflow might fail mistakenly because of a Keda scale-down operation following the deployment, leading to a `curl` exit code of 28 in `test_url` within `deploy` script.
This modification will raise the retry count from 10 to 15 times.
> chore: change connection test retry from 10 to 15 times

- .github/workflows/cd.yaml
- .github/workflows/codeql-analysis.yml
- src/deploy/resources/base/deployment.yml
- src/deploy/resources/base/patches/deployment.patch.json
https://app.shortcut.com/findhotel/story/153220/adjust-datadog-service-name-from-icp-systems
ref.: https://github.com/FindHotel/daedalus/pull/12162
This PR aims to set the proper Datadog environment variables to configure the service name of the review environments; otherwise, Datadog will use the IMAGE name as the source, e.g.:
- Before:
- After:
> feat: setting datadog environment variables
